# Error registry to register errors with the GOCFL error factory.
# Docs: https://pkg.go.dev/github.com/ocfl-archive/error/pkg/error#Error

[[errors]]
id = "ErrorGOCFL"
type = "GOCFL"
weight = 50
message = "" # e.g. errors in GOCFL execution

[[errors]]
id = "LogGOCFL"
type = "GOCFL"
weight = 20
message = "" # e.g. reports duration

# System errors that might be encountered during startup and processing.

[[errors]]
id = "LogExtensionInit"
type = "INITIALIZATION"
weight = 50
message = "initializing extensions" # e.g. adding creators for extenstions

[[errors]]
id = "ErrorExtensionInit"
type = "INITIALIZATION"
weight = 60
message = "error initializing extensions"

[[errors]]
id = "LogValidationStatus"
type = "VALIDATION"
weight = 60
message = "ocfl validation status" # e.g. reports no errors found

[[errors]]
id = "ErrorValidationStatus"
type = "VALIDATION"
weight = 70
message = "ocfl validation error"

[[errors]]
id = "LogExtensionConfig"
type = "CONFIGURATION"
weight = 50
message = "configuring extensions"

[[errors]]
id = "ErrorExtensionRunner"
type = "EXTENSIONRUNNER"
weight = 50
message = "problem with the given ocfl extension"

[[errors]]
id = "ErrorOCFL"
type = "UPDATE"
weight = 50
message = "in the ocfl module" # e.g. not object not writeable.

[[errors]]
id = "LogOCFL"
type = "UPDATE"
weight = 20
message = "in the ocfl module" # e.g. adding content, status, etc.

[[errors]]
id = "ErrorOCFLCreation"
type = "UPDATE"
weight = 50
message = "error with GOCFL write processes, e.g. creation or update"

[[errors]]
id = "ErrorOCFLEnd"
type = "UPDATE"
weight = 50
message = "error ending GOCFL process, e.g. creation or update"

[[errors]]
id = "ErrorFS"
type = "FILESYSTEM"
weight = 80
message = "filesystem abstraction issue"

# Extension errors

[[errors]]
id = "ErrorThumbnailExtension"
type = "GENERATE THUMBNAIL"
weight = 50
message = "thumbnail extension module" # Potentially substantial: errors around GOCFL thumbnail generation.

[[errors]]
id = "LogThumbnailExtension"
type = "GENERATE THUMBNAIL"
weight = 20
message = "thumbnail extension module" # Largely informational: GOCFL's attempt to create Thumbnails

# Indexer errors affecting preservation.

[[errors]]
id = "ErrorIndexerSiegfried"
type = "PRESERVATION"
weight = 70
message = "indexer: siegfried returned an error"

[[errors]]
id = "ErrorIndexerXML"
type = "PRESERVATION"
weight = 70
message = "indexer: xml returned an error"

[[errors]]
id = "ErrorIndexerChecksum"
type = "PRESERVATION"
weight = 70
message = "indexer: checksum returned an error"

[[errors]]
id = "ErrorIndexerTika"
type = "PRESERVATION"
weight = 70
message = "indexer: tika returned an error"

[[errors]]
id = "ErrorIndexerFFProbe"
type = "PRESERVATION"
weight = 70
message = "indexer: ffprobe returned an error"

[[errors]]
id = "ErrorIndexerIdentify"
type = "PRESERVATION"
weight = 70
message = "indexer: identify returned an error"  # e.g. error executing (convert [XML:- json:-]) (imagemagick).

[[errors]]
id = "ErrorIndexerFullText"
type = "PRESERVATION"
weight = 70
message = "indexer: full-text returned an error"
